# Generated by Django 5.1 on 2024-09-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPost', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
